#!/usr/bin/env bash

for tc in $(./run ls); do
    echo $tc
    source activate-master
    printf "    master: "
    ./run stat "$tc" 2>/dev/null | grep "seconds time elapsed"
    source activate
    printf "    updated:"
    ./run stat "$tc" 2>/dev/null | grep "seconds time elapsed"
done
