#!/usr/bin/env bash

# This assumes the caller has set the PATH to contain the
# `opensim-cmd` that should be measured as top-prio
which opensim-cmd

pushd ToyDropLanding/
cmd="opensim-cmd run-tool setup_forward_tool.xml"
valgrind --tool=callgrind --cache-sim=yes --branch-sim=yes  -- ${cmd}
perf record --freq 8192 -- ${cmd}

# cleanup *run* artifacts (not perf measurements)
rm -rf '\\forward' err.log out.log perf.data.old
popd
